sudo: false
language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements_dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest -vv --cov=backbits --cov-report xml --ignore=./backbits/frontbits
after_script:
  - ./cc-test-reporter after-build -d -t coverage.py --exit-code $TRAVIS_TEST_RESULT