version: '3'
services:

  # mongoDB container
  mongodb:
    image: mongo:3.6.0
    ports: 
      - "27017:27017"

  # main app container
  web:  
    build: .
    volumes:
     - .:/mybits
    env_file: .env
    ports:
     - "${APP_PORT}:${APP_PORT}"
    depends_on:
     - mongodb
    command:
      ["./wait-for-it.sh", "mongodb:27017", "-t", "30", "--",
       "./docker-entrypoint.sh"]