version: '3'
services:

  # nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/nginx.local.conf:/etc/nginx/nginx.conf
      - ./static/mybits:/var/www/mybits/static/mybits/  # root for static files
      - ./media/mybits:/var/www/mybits/media/mybits/  # root for static files
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  # mysql
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=mybits_db
      - MYSQL_USER=conkers
      - MYSQL_PASSWORD=badfurday
    volumes:
      - ./.db:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

  # main app container
  web:
    build: .
    volumes:
     - .:/mybits
    env_file: .env
    ports:
     - "${APP_PORT}:${APP_PORT}"
    depends_on:
     - db
    command:
      ["./wait-for-it.sh",
       "db:3306", "-t", "120", "--",
       "./docker-entrypoint.sh"]