version: '3'
services:

  # mysql
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=mybits_db
      - MYSQL_USER=conkers
      - MYSQL_PASSWORD=badfurday
    volumes:
      - ./dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

  # main app container
  web:  
    build: .
    volumes:
     - .:/mybits
    env_file: .env
    ports:
     - "${APP_PORT}:${APP_PORT}"
    depends_on:
     - db
    command:
      ["./wait-for-it.sh", "db:3306", "-t", "30", "--",
       "./docker-entrypoint.sh"]