# Generated by Django 2.0.5 on 2018-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='static/backbits')),
                ('resume', models.FileField(upload_to='static/backbits')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='static/backbits')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='static/backbits')),
            ],
        ),
    ]
