# Generated by Django 2.1.7 on 2019-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.FileField(upload_to='backbits'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(upload_to='backbits'),
        ),
    ]
