# Generated by Django 2.1.7 on 2019-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbits', '0002_auto_20190304_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='backbits'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(upload_to='backbits'),
        ),
    ]
